### PR TITLE
Quest submission: dustin, feb29

### PR DESCRIPTION
**Pull request by CocDap**

### CODE REVIEW

**Comment by sacha-l** [comment]
Hi Dustin! Congrats on completing the workshop quest! Please complete this form and submit your KSM address to collect your reward: https://forms.gle/fCfcDmtV79xA4eQD9 🚀

**Comment by CocDap** [comment]
hi @sacha-l . Thank you for organizing this valuable workshop. I have completed Quest 1 and Quest 2 and have submitted the form. Please check again. My email is `hodinhdung1997@gmail.com`

**Comment by sacha-l** [comment]
Awesome, I got a little confused but it's clear now! Thanks for doing the workshop and congrats on completing it =)

Sent! See transaction details: https://kusama.subscan.io/tx/0x392284d52160a1f1a732f0c8584ae10afcdf5f3e1f31603d546c6e3b8f7d7202

Learn more about Kusama here: https://kusama.network/

Have a great day. 🚀

**Comment by CocDap** [comment]
> Awesome, I got a little confused but it's clear now! Thanks for doing the workshop and congrats on completing it =)
> 
> Sent! See transaction details: https://kusama.subscan.io/tx/0x392284d52160a1f1a732f0c8584ae10afcdf5f3e1f31603d546c6e3b8f7d7202
> 
> Learn more about Kusama here: https://kusama.network/
> 
> Have a great day. 🚀

Thank you so much. I hope there will be more workshops like this to understand Polkadot ecosystem

**Pull request merged**
