### PR TITLE
Quest submission: duonghb, mar02

### PR DESCRIPTION
**Pull request by duonghb53**

### CODE REVIEW

**Comment by duonghb53** [comment]
@sacha-l please check PR, bro.

**Comment by sacha-l** [comment]
Hi @duonghb53 ! Sorry I missed this while I was in Denver. How come this came in 2 days later? Usually I wouldn't accept this as participation unless you can prove to me that you were at the event. I also never received your feedback submission from the form that I sent out at the end of the workshop.

**Comment by duonghb53** [comment]
> Hi @duonghb53 ! Sorry I missed this while I was in Denver. How come this came in 2 days later? Usually I wouldn't accept this as participation unless you can prove to me that you were at the event. I also never received your feedback submission from the form that I sent out at the end of the workshop.

@sacha-l sorry, I'm missing this, I completed feedback submission. I have a friend share this mission and do it late 2 days.

**Comment by sacha-l** [comment]
KSM sent! See transaction details: https://kusama.subscan.io/account/E7msm7vP2VKQd5KrZo8SZ9fwr63kCsMhhbND1ZxM7JKKwat

Learn more about Kusama here: https://kusama.network/

Have a great day. 🚀

**Comment by duonghb53** [comment]
@sacha-l thank you

**Pull request merged**
