### PR TITLE
Quest submission: jinu, feb28

### PR DESCRIPTION
**Pull request by lj1nu**

### CODE REVIEW

**Comment by sacha-l** [comment]
Hey @lj1nu ! Congrats on completing the quest. 🚀

Can you please confirm that this is the KSM address you want to receive your rewards on: HS1Hj2KQGV1e6idpDUMYQXph2y7ndNJnRcL3h13n6CHkN1R 

This is the address derived by the Substrate address you provided in your quest submission. Address transforms can be checked using this tool: https://sub.id/5GvPdQgSmuU5tSuC3WfJeTApYSgsyxZ8L3maf2j6JHyo1GRp

**Comment by sacha-l** [comment]
Or is it this?

HZmu4PVwsraM3DM6jHuH19FkMmmgw2qsVshQdU5NQR5tCc9

**Comment by lj1nu** [comment]
HS1Hj2KQGV1e6idpDUMYQXph2y7ndNJnRcL3h13n6CHkN1R that's right
thx @sacha-l

**Comment by sacha-l** [comment]
Awesome. Thanks for doing the workshop and congrats on completing it =)

KSM sent! See transaction details: https://kusama.subscan.io/tx/0x97d1d92a89f177cd16db86d6197f0e52b26f508ff3de4676bc399f2b08b76d8f

Learn more about Kusama here: https://kusama.network/

Have a great day. 🚀

**Pull request merged**
